"use client";

import { useQrCode } from "./useQrCode";
import WosoolMark from "./WosoolMark";

interface Props {
  /** Data to encode. Default: Wosool homepage. */
  data?: string;
  /** Width of the outer card in px */
  width?: number;
  /** Mint glow (used during scanning scene) */
  glow?: boolean;
  /** Wosool logo tile in center */
  center?: boolean;
  /** Logo tile size in px */
  centerSize?: number;
  /** Card padding in px */
  padding?: number;
}

export default function QrCode({
  data = "https://wosool.ai",
  width = 360,
  glow = false,
  center = true,
  centerSize = 72,
  padding = 22,
}: Props) {
  const svg = useQrCode(data);

  return (
    <div
      style={{
        width,
        padding,
        borderRadius: 20,
        background: "var(--w-surface)",
        border: glow ? "1px solid var(--w-mint-500)" : "1px solid var(--w-border)",
        boxShadow: glow
          ? "0 0 0 6px rgba(115, 252, 215, 0.35), 0 0 0 14px rgba(115, 252, 215, 0.12)"
          : undefined,
        position: "relative",
        transition: "box-shadow 200ms ease-out",
      }}
    >
      <div
        aria-label="QR code"
        style={{ width: "100%", aspectRatio: "1", display: "block" }}
        // svg is generated by our trusted qrcode library, not user input
        dangerouslySetInnerHTML={svg ? { __html: svg } : undefined}
      />
      {center && (
        <div
          style={{
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
            width: centerSize,
            height: centerSize,
            borderRadius: 14,
            background: "var(--w-mint-500)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            boxShadow: "0 0 0 6px var(--w-surface)",
          }}
        >
          <WosoolMark size={centerSize * 0.67} />
        </div>
      )}
    </div>
  );
}
